version: '3'

services:
  chowkidar:
    build: .
    user: root
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/chowkidar
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - db
      - scheduler

  nginx:
      image: nginx:stable
      restart: always
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - chowkidar

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=scanner
      - MYSQL_USER=scanner
      - MYSQL_PASSWORD=scanner
      - MYSQL_DATABASE=scanner
    volumes:
      - .data/mysql:/var/lib/mysql

  scheduler:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"